### ISSUE TITLE
when matched word is inside the fold, auto expand the fold.

### ISSUE THREAD

**Issue by ninrod** [timakro/vim-searchant#10]
hi, great plugin, thank you. I have one nagging issue to report though. 

Standard vim behaviour is to expand the fold if the fold is closed, but a matched word lies inside the fold. 

When I install your plugin, this does not happens anymore and I have to manually open all my folds until the matched word appears before my eyes. 

I think this is a bug.

**Comment by timakro** [comment]
This seems to be an side effect of mapping additional actions to the enter key in command line mode. The shortest way to reproduce this is `cmap <CR> <CR>` this could be considered a bug in Vim.

**Comment by timakro** [comment]
Actually as a workaround the plugin can just execute `zo` after every successful search.
