### ISSUE TITLE
colouring in tmux

### ISSUE THREAD

**Issue by musoke** [timakro/vim-searchant#12]
I like this plugin!

However, it seems like colouring of the current result doesn't work in tmux.

I have tried tmux 1.8 and 2.2 with vim 7.4.

**Comment by timakro** [comment]
I don't use tmux so I won't look into this, sorry!

**Comment by musoke** [comment]
OK -- I'll let you know if I find a solution.

**Comment by musoke** [comment]
Seems to have resolved itself... possibly due to a vim or tmux update?
