### ISSUE TITLE
Make mappings optional, use <Plug>s

### ISSUE THREAD

**Issue by davidosomething** [timakro/vim-searchant#14]
This plugin is compatible with others like vim-asterisk and vim-anzu -- but only if you manually map them as recursive `nmap`s. Can you add an option to disable mapping and provide a <Plug> version that just runs `s:MapUpdate`?

I've tested on my own vimrc by unmapping the \* mapping (since the `nnoremap` from searchant prevents mine from working)
https://github.com/davidosomething/dotfiles/blob/cdfc9ba4e4d0c58e7ac60352dd9a37f73032541e/vim/after/plugin/search.vim#L42-L45

**Comment by timakro** [comment]
Would it be okay for you to execute your `search.vim` after loading the plugins (like you do for testing searchant: https://github.com/davidosomething/dotfiles/commit/cdfc9ba4e4d0c58e7ac60352dd9a37f73032541e)? Then this could be solved by making searchant keep mappings defined by the user or other plugins and just add its functionality.

**Comment by davidosomething** [comment]
Sure, I don't mind keeping plugin conf it in an `after/plugin`
