### ISSUE TITLE
NVIM v0.2.1-dev got this

### ISSUE THREAD

**Issue by lasypig** [timakro/vim-searchant#15]
```
Error detected while processing function <SNR>54_Update[1]..<SNR>54_Stop:                                                                                                                                                                      
line    3:
E803: ID not found: 2428
```

**Comment by timakro** [comment]
Could you explain how to reproduce this?

**Comment by timakro** [comment]
I don't use Neovim and won't look into this. The error occurs when trying to delete a match for highlighting, this is the relevant code:

```
let w:current_match_id = matchadd("SearchCurrent", pattern, 2)
```

```
if exists("w:current_match_id")
    call matchdelete(w:current_match_id)
    unlet w:current_match_id
endif
```

Possibly there is a difference with the scope of matches (this script excepts it to be window wide) in Neovim which causes this.

**Comment by lasypig** [comment]
@timakro Thanks, maybe it is a new nvim bug.

**Comment by timakro** [comment]
vim-searchant is obsolete. You should use [vim-searchhi](https://github.com/qxxxb/vim-searchhi) instead.
