### ISSUE TITLE
Breaks `c/` motion

### ISSUE THREAD

**Issue by hibachrach** [timakro/vim-searchant#16]
This plugin breaks `c/` which allows one to change (`c`) up to a search query (entered after `/`). It looks like this function

https://github.com/timakro/vim-searchant/blob/1bd7f074c53f74c6a87f0abe9220adeb3c82f9c3/plugin/searchant.vim#L63-L71

doesn't handle the case where it is part of a motion. I'm still a beginner at VimL so I'm not quite sure what the fix is off the top of my head, but hopefully it shouldn't be too tough. If I figure out something I'll open a PR.

**Comment by timakro** [comment]
I couldn't find a way to detect if the `c` command was used, if we were able to detect this the `<Ctrl-o>` command in insert mode could be used to execute one command in command-line mode. Let me know if you figure something out.
