### ISSUE TITLE
[Feature Request] option to not expand folds automatically

### ISSUE THREAD

**Issue by andykais** [timakro/vim-searchant#17]
I see that `v1.0.6` added the functionality to always open folds when searching. Could we add the option to just walk over folds if desired? In native vim search, this can be done with the option
```vim
set foldopen-=search
```
but that is overlooked with this plugin enabled. I am willing to make a PR for this if it would be welcome!

**Comment by timakro** [comment]
Very welcome! I'd be happy to accept a PR.
