### ISSUE TITLE
make it dissappear on :nohl

### ISSUE THREAD

**Issue by izelnakri** [timakro/vim-searchant#18]
How can we make this possible? I have a keybind that toggles off search highlights, `<Leader>h -> :nohl`

but when I have a selection already on the results, SearchCurrent stays on the page.

**Comment by timakro** [comment]
There is an in-built function to stop all search highlighting, is that what you're looking for? By default the plugin binds it to `CTRL+C`. You can change it to another key like this:

    let g:searchant_map_stop = 0
    nmap <Leader>h <Plug>SearchantStop

**Comment by izelnakri** [comment]
Nohl disables highlighting until the next highlight. Ill check if this does the same as well, otherwise we should implement it.

**Comment by izelnakri** [comment]
`<Plug>SearchantStop` works, thank you! Lets document this on README

**Comment by timakro** [comment]
It is in the vim documentation for the plugin https://github.com/timakro/vim-searchant/blob/master/doc/searchant.txt.
