### ISSUE TITLE
How to get new "set shortmess-=S" back

### ISSUE THREAD

**Issue by voyeg3r** [timakro/vim-searchant#21]
Vim has a patch that allows us to show a count of the search match, something like:  "[3/15]" at the bottom of screen. vim-sehrchant is not giving me this results

For now I have disabled vim-searchant ultil I can figure out a solution to this issue

There is a full discussion [here](https://github.com/vim/vim/pull/4446) about the new feature, because it breaks 
    `nnoremap n nzz`

**Comment by timakro** [comment]
vim-searchant is obsolete. You should use [vim-searchhi](https://github.com/qxxxb/vim-searchhi) instead.
