### ISSUE TITLE
Leading wildcard symbol in search causes "NFA regexp" error

### ISSUE THREAD

**Issue by antoineco** [timakro/vim-searchant#24]
**Repro**

Search for a pattern that actually exists in the file with a leading wildcard symbol (e.g. `/*foo`)

```sh
# foo.txt
x = *foo
```

The following error is thrown:

```
Error detected while processing function <SNR>58_Start:                                                                                                     line    9:
E866: (NFA regexp) Misplaced *
E475: Invalid argument: \m\%27l\%21c\%(*foo\m\)\c
Press ENTER or type command to continue
```

The wildcard symbol in my example is a typo, I should have escaped it with `/\*foo`. However, I noticed that Vim interprets leading wildcards as a literal `*`.

Not sure if you have any interest in fixing this, but I figured I could report anyway.

**Comment by timakro** [comment]
vim-searchant is obsolete. You should use [vim-searchhi](https://github.com/qxxxb/vim-searchhi) instead.
