### ISSUE TITLE
<C-C> doesn't always work

### ISSUE THREAD

**Issue by Dupond** [timakro/vim-searchant#25]
Hello,

The key mapping to stop the search highlighting doesn't work in certain cases with multiple vim windows. Here's what happens to me sometimes:

1. I search for a word: `/word`
2. I open a new window/split: `<Ctrl>+<w>` then press `<v>` (at this step, the same buffer is opened in the two windows, all the matches in the two windows are highlighted, and the active window (where my cursor is) is the newly created one, so the right one)
3. I do some work, then try to stop the search highlighting: `<Ctrl>+<c>`

But nothing happens: all the matches in the two windows remain highlighted. I have to move back to the left window to be able to stop it.

This is particularly anoying in a `vimdiff`: I search for a word in the left pane, switch to the right to modify it, then later on wonder why I can't stop the search highlighting, and have to remember that I launched it from the left pane...

Is there any way to solve this? Thanx in advance for your help!

**Comment by antoineco** [comment]
@Dupond ~I don't think C-C is supposed to clear the search highlighting, is it?~ edit: my bad, it's in the docs.

This is what I use in my `vimrc`, it works with vimdiff:
```vim
let g:searchant_map_stop = 0
nmap <silent> <C-L> <Plug>SearchantStop:diffupdate<Bar>redraw!<CR>
```

**Comment by Dupond** [comment]
No, it doesn't work: when you search for a word from a certain window, you can't stop it from another one with your keybind.

The problem is that, by default, one search is applied to all the opened windows and buffers; so it doesn't make sense to only be able to stop it from the window it has been launched. The "SearchantStop" keybind should be applied to all the opened windows and buffers, but currently it isn't.

**Comment by antoineco** [comment]
Ok I didn't get that from the first comment. Thanks for clarifying 👍

**Comment by timakro** [comment]
vim-searchant is obsolete. You should use [vim-searchhi](https://github.com/qxxxb/vim-searchhi) instead.
