### ISSUE TITLE
Color change does not work

### ISSUE THREAD

**Issue by holmescharles** [timakro/vim-searchant#26]
If I install this plugin, it works as advertised (current search is red, other matches are yellow), but if I add the following to my vimrc:

```
highlight SearchCurrent ctermbg=cyan
```

the color distinction disappears (all matches are yellow, as though the plugin were not installed). 

Any idea what the issue might be?
Also, I am using neovim if that helps.

**Comment by crowdmarkos** [comment]
I could not get that highlight mapping to work so I made a hack workaround.

Add these lines to the top of`vim-searchant/plugin/searchant.vim`

```
let g:searchant_search_current = get(g:, 'searchant_search_current', 1)

" Default highlight current style
if exists('g:searchant_search_current')
	execute('highlight SearchCurrent ' . g:searchant_search_current)
endif
```

And add this line to your `.vimrc` (change around the colours to whatever you want. This is a navy colour.

```
let g:searchant_search_current = 'ctermfg=0 ctermbg=12 guifg=#000000 guibg=#005fff'
```

I'm not very well versed in Vim so I would love to see a more appropriate fix to this.

**Comment by timakro** [comment]
vim-searchant is obsolete. You should use [vim-searchhi](https://github.com/qxxxb/vim-searchhi) instead.
